### ISSUE TITLE
Preliminary design notes 

### ISSUE THREAD

**Issue by traversaro** [traversaro/not-working-meshcat-cpp#1]
C++ port of https://github.com/rdeits/meshcat-python / https://github.com/rdeits/MeshCat.jl (actually they are quite different). 

# Client code 
 * Open a webbrowser from code (py equivalent: https://docs.python.org/2/library/webbrowser.html ) 
    * Good old `system` ? 
      * Probably something like https://github.com/DaanDeMeyer/reproc or something similar is more appropriate
 * Encode messages using json/msgpack
    * https://github.com/msgpack/msgpack-c
    * https://github.com/ar90n/msgpack11 
Note that https://github.com/rdeits/meshcat#websocket-api: "Note that we do support the MsgPack extension types listed in msgpack-lite#extension-types, and the Float32Array type is particularly useful for efficiently sending point data."
# Server code  
* WebSockets 
  * https://github.com/uNetworking/uWebSockets
  * https://github.com/zaphoyd/websocketpp
  * https://github.com/facundofarias/awesome-websockets#c-1

# Both 
* ZMQ 
  * https://github.com/zeromq/cppzmq

**Comment by traversaro** [comment]
Note that the MeshCat.jl actually dropped the intermediate ZMQ protocol in https://github.com/rdeits/MeshCat.jl/pull/28 .

**Comment by traversaro** [comment]
Relevant discussion: https://github.com/RobotLocomotion/drake/issues/13038#issuecomment-898651400 .

**Comment by traversaro** [comment]
See https://github.com/GiulioRomualdi/meshcat-cpp for a working MVP, thanks to @GiulioRomualdi .

**Comment by GiulioRomualdi** [comment]
Here https://github.com/GiulioRomualdi/idyntree-meshcat-cpp, I utilized the c++ interface to show a multi-body system with iDynTree
